Proxy Server Initial Commit
cloudimix/k3s-Kubespray-EFK-Prometheus pull request #3
Opened 2022-02-17 02:33 UTC by cloudimix

2022-02-17 08:51 UTC, delfer requested changes
Есть несколько критических замечаний

2022-02-17 08:51 UTC, delfer commented on 4.1_http_proxy/core.tf
> +
путые строки в начале файлы не нужны

2022-02-17 08:51 UTC, delfer commented on 4.1_http_proxy/core.tf
> +    "ssh_authorized_keys" = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDd/AbdMC2UxwrdZSB0g6HImASnBoktedmWM5nZawLjrj/cAM5ic5/TuazxKRo/tpXY4CwYakt19+quvvJXR3M7qUl1HuiYdogJ4cvqZxgCUcQGwGyB3YYRWI0OjJihSHXFPE
ключ не нужно хардкодить, лучше вынести в переменные, и лучше это сделать так, чтобы можно было задавать несколько ключей. Еще лучше сделать так, чтобы ключи не лежали в репозитории, а брались из переменных репозитория при сборке (или из terraform cloud, там тоже можно хранить секреты).
Основная идея - чтобы кто угодно мог взять репозиторий и как есть его переиспользовать, не внося ни единой правки. Все то, что относится конкретно к тебе и к твоей инсталляции, все должно быть вынесено из файлов проекта в переменные среды сборки. Плюс в Readme должно быть описано какие переменные нужно задавать. Для примерно можно посмотреть мой проект https://github.com/delfer/spot-mc - права readme я не дописал.

2022-02-17 08:51 UTC, delfer commented on 4.1_http_proxy/core.tf
> +    "ssh_authorized_keys" = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDd/AbdMC2UxwrdZSB0g6HImASnBoktedmWM5nZawLjrj/cAM5ic5/TuazxKRo/tpXY4CwYakt19+quvvJXR3M7qUl1HuiYdogJ4cvqZxgCUcQGwGyB3YYRWI0OjJihSHXFPE
переменные, аналогично

2022-02-17 08:51 UTC, delfer commented on 4.1_http_proxy/core.tf
> +  vcn_id = oci_core_vcn.MainVCN.id
похоже форматирование немного съехало, нужно сделать terraform lint

2022-02-17 08:51 UTC, delfer commented on 4.1_http_proxy/makefile
> +	sleep 50
sleep в проектах не должно быть никогда, это огромный кусок неопределнности и может приводить к тому, что один и тот же код может работать или выдавать ошибку. В твоем случае можно заменить на ansible.builtin.wait_for_connection

2022-02-17 08:51 UTC, delfer commented on 4.1_http_proxy/provider.tf
> +
пустая строка

2022-02-17 08:51 UTC, delfer commented on 4.1_http_proxy/roles/squid_proxy_setup/tasks/main.yml
> +  apt:  name=squid state=present
в 5 строке был тот же вызов apt, нет смысла делать два вызова, можно объединить

2022-02-17 08:51 UTC, delfer commented on 4.1_http_proxy/roles/squid_proxy_setup/tasks/main.yml
> +    state: present
до этого место ранее везде использовался синтаксис `module: key=value [key=value] ...` тут уже другой синтаксис - yaml. Хотя все можно было писать и так и так. Лучше переделать все на yaml синтаксис как в этой таске

2022-02-17 08:51 UTC, delfer commented on 4.1_http_proxy/roles/squid_proxy_setup/tasks/main.yml
> +  shell: "sudo iptables -I INPUT 6 -p tcp  --match multiport --dports 80,3128,443 -j ACCEPT"
это правило исчезнет после перезапуска сервера. Нужно:

1. Разобраться как сохранять правила iptables
2. Разобраться как все-таки переиспользовать существующий модуль iptables
3. Так как уже есть фаерволл на уровне облака, можно внутри ВМ отключить iptables

2022-02-17 08:51 UTC, delfer commented on 4.1_http_proxy/roles/squid_proxy_setup/vars/main.yml
> +  password: 123456
креды нужно хранить в зашифрованном виде https://docs.ansible.com/ansible/latest/user_guide/vault.html
Одно из самых важных правил информационной безопасности - пароли не должны нигде и ни при каких обстоятельствах встречаться в открытом виде - ни на инструментальном компьютере, ни на сервере, ни в выводе программ, ни в логах.

2022-02-17 08:51 UTC, delfer commented on 4.1_http_proxy/roles/squid_proxy_setup/vars/main.yml
> +  - .oracle.com
в контексте данной задачи нет смысла в двух отдельных whitelist и proxy_pac_domains, в них по сути одно и то же. Должна быть одна переменная без копипасты. Нужно будет только подумать как их подставить в файлы на сервере через шаблоны Jinja2

2022-06-19 00:43 UTC, cloudimix commented on 4.1_http_proxy/ansible.cfg
> +host_key_checking = false
Убрал для теста, но при запуске вышло сразу несколько строк по поводу фингерпринта (поднимал 4 сервера). Смог залогинится только на последний хост. В принципе, в этой задаче больше одно хоста не нужно, можно и убрать.

2022-06-19 00:45 UTC, cloudimix commented on 4.1_http_proxy/core.tf
> +
ok

2022-06-19 00:50 UTC, merged

2022-06-19 00:58 UTC, cloudimix commented on 4.1_http_proxy/dynamic_inventory.py
> +        w.write(i+"\n")
Переделал. Работает )

2022-06-26 13:43 UTC, cloudimix commented on 4.1_http_proxy/roles/squid_proxy_setup/tasks/main.yml
> +  shell: "sudo iptables -I INPUT 6 -p tcp  --match multiport --dports 80,3128,443 -j ACCEPT"
Не понимаю почему, но через модуль iptables не получается. Сделаю через cron